<a href="https://colab.research.google.com/github/anmay-kaushik/mlearning/blob/main/featurescaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import preprocessing

In [3]:
X = np.array([[ 1., -1., 2.],
              [2., 0., 0.,],
              [0., 1., -1,]])

In [4]:
X_scaled = preprocessing.scale(X)


In [5]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [7]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [6]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [8]:
scaler = preprocessing.StandardScaler().fit(X)
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [9]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])